
Charles_Robert_Darwin_by_John_Collier.jpg:
	curl -o Charles_Robert_Darwin_by_John_Collier.jpg --fail https://www.dasgehirn.info/sites/default/files/styles/scale_1280_w/public/teaser/Charles_Robert_Darwin_by_John_Collier.jpg
